//! Typed client **codegen** from a contract's on-chain interface.
//!
//! On EVM chains, generating a typed client means hunting down an ABI file and
//! hoping it matches what's deployed. A Soroban contract *ships* its interface
//! on-chain (see [`crate::spec`]), so a typed client can be generated from the
//! chain itself, with zero configuration — and regenerated the moment the
//! upgrade watch sees the interface change.
//!
//! The generated TypeScript is self-contained (platform `fetch`, no runtime
//! dependencies) and calls the contract's view functions through Lumenqraph's
//! read layer (`POST /contracts/:id/call`). Because the read layer names UDT
//! values in results (see [`crate::read::decode_result`]), one generated type
//! per user-defined type is honest in *both* directions: what a call returns is
//! shaped exactly like what the next call accepts.
//!
//! Output is deterministic — same spec in, same source out — so it can be
//! cached, tested, and diffed across interface versions.

use std::collections::BTreeSet;
use std::fmt::Write;

use stellar_xdr::curr::ScSpecTypeDef;

use crate::spec::{ContractSpec, FunctionSpec, UdtStruct};

/// Scalar type aliases the generated code may reference: name, definition, doc.
/// Only the ones actually used by the contract's interface are emitted.
const ALIASES: &[(&str, &str, &str)] = &[
    (
        "Address",
        "string",
        "A Stellar strkey address (`G…` account or `C…` contract).",
    ),
    (
        "Bytes",
        "string",
        "Hex-encoded bytes (`0x` prefix optional on input; results are `0x`-prefixed).",
    ),
    ("u64", "number | string", INT_DOC),
    ("i64", "number | string", INT_DOC),
    ("u128", "number | string", INT_DOC),
    ("i128", "number | string", INT_DOC),
    ("u256", "number | string", INT_DOC),
    ("i256", "number | string", INT_DOC),
    (
        "Timepoint",
        "number | string",
        "Seconds since the Unix epoch; returned as a decimal string.",
    ),
    (
        "Duration",
        "number | string",
        "A span of seconds; returned as a decimal string.",
    ),
];

const INT_DOC: &str =
    "Pass a decimal string (safe at any size) or a number; returned as a decimal string.";

/// Where a type appears. Arguments are type-checked by the encoder, so types it
/// rejects become `never`; results come from the generic decoder, so the same
/// types map to what decoding actually produces.
#[derive(Clone, Copy, PartialEq)]
enum Pos {
    Arg,
    Ret,
}

/// Generate a self-contained typed TypeScript client for `contract_id` from its
/// parsed on-chain interface.
pub fn typescript_client(contract_id: &str, spec: &ContractSpec) -> String {
    let mut g = Gen {
        spec,
        used: BTreeSet::new(),
    };

    // Render the interface-dependent parts first, so the prelude can include
    // exactly the scalar aliases they turned out to use.
    let udts = g.render_udts();
    let methods = g.render_methods();
    let prelude = g.render_prelude();

    let mut out = String::new();
    let _ = write!(
        out,
        "\
// Typed client for the Soroban contract
//   {contract_id}
//
// Generated by Lumenqraph from the contract's *on-chain* interface (the
// `contractspecv0` section of its deployed WASM) — no ABI file, no config.
// Calls go through Lumenqraph's read layer, which type-checks arguments
// against the same on-chain spec before they ever reach the network.
//
// Zero dependencies: works anywhere `fetch` exists (browser, Node 18+,
// Deno, Bun).
//
//   const contract = new ContractClient({{ baseUrl: \"https://…\" }});
//
// Regenerate any time from `GET /contracts/{contract_id}/sdk?lang=ts`.
// If the contract is upgraded on-chain, Lumenqraph's upgrade watch records
// it — `GET /contracts/{contract_id}/interface/history` shows what changed.
{prelude}{udts}
export interface ClientOptions {{
  /** Lumenqraph API base URL, e.g. \"https://lumenqraph.onrender.com\". */
  baseUrl: string;
  /** API key, sent as `x-api-key` (only needed if the server requires one). */
  apiKey?: string;
  /** Override the fetch implementation (defaults to global fetch). */
  fetch?: typeof fetch;
}}

export interface CallOptions {{
  /** Optional `G…` source account for the read-only simulation. */
  sourceAccount?: string;
}}

/** Error thrown for any non-2xx API response (bad arguments, trapped call…). */
export class CallError extends Error {{
  constructor(
    message: string,
    readonly status: number,
    readonly body: unknown,
  ) {{
    super(message);
    this.name = \"CallError\";
  }}
}}

export class ContractClient {{
  /** The on-chain contract this client is bound to. */
  static readonly contractId =
    \"{contract_id}\";

  constructor(private readonly opts: ClientOptions) {{}}
{methods}
  /** POST the typed call to the API and unwrap the decoded result value. */
  private async invoke(fn: string, args: unknown, opts?: CallOptions): Promise<unknown> {{
    const doFetch = this.opts.fetch ?? globalThis.fetch;
    const base = this.opts.baseUrl.replace(/\\/+$/, \"\");
    const headers: Record<string, string> = {{ \"content-type\": \"application/json\" }};
    if (this.opts.apiKey) headers[\"x-api-key\"] = this.opts.apiKey;
    const res = await doFetch(`${{base}}/contracts/${{ContractClient.contractId}}/call`, {{
      method: \"POST\",
      headers,
      body: JSON.stringify({{ function: fn, args, source_account: opts?.sourceAccount ?? null }}),
    }});
    const text = await res.text();
    let body: unknown = null;
    try {{
      body = text ? JSON.parse(text) : null;
    }} catch {{
      body = text;
    }}
    if (!res.ok) {{
      const msg =
        (body as {{ error?: string }} | null)?.error ?? `${{res.status}} ${{res.statusText}}`;
      throw new CallError(msg, res.status, body);
    }}
    return (body as {{ result?: {{ value?: unknown }} }}).result?.value ?? null;
  }}
}}
"
    );
    out
}

struct Gen<'a> {
    spec: &'a ContractSpec,
    /// Scalar aliases referenced so far (names index into [`ALIASES`]).
    used: BTreeSet<&'static str>,
}

impl Gen<'_> {
    /// Reference a scalar alias by name, recording the use — unless the
    /// contract defines a UDT with the same name, in which case the raw type is
    /// inlined so the two can't collide.
    fn alias(&mut self, name: &'static str) -> String {
        if self.has_udt(name) {
            // `alias()` is only called with names that appear in ALIASES; the
            // find is always infallible.
            #[allow(clippy::expect_used)]
            let (_, def, _) = ALIASES
                .iter()
                .find(|(n, _, _)| *n == name)
                .expect("name is always an ALIASES key; callers only pass ALIASES names");
            return (*def).to_string();
        }
        self.used.insert(name);
        name.to_string()
    }

    fn has_udt(&self, name: &str) -> bool {
        self.spec.structs.iter().any(|s| s.name == name)
            || self.spec.unions.iter().any(|u| u.name == name)
            || self.spec.enums.iter().any(|e| e.name == name)
    }

    /// Map a spec type to TypeScript. `pos` only matters for the handful of
    /// types the encoder can't take as arguments — everything else reads and
    /// writes as the same shape (see the module docs on result relabelling).
    fn ts(&mut self, ty: &ScSpecTypeDef, pos: Pos) -> String {
        use ScSpecTypeDef as T;
        match ty {
            T::Bool => "boolean".into(),
            T::Void => "null".into(),
            T::U32 | T::I32 => "number".into(),
            T::U64 => self.alias("u64"),
            T::I64 => self.alias("i64"),
            T::U128 => self.alias("u128"),
            T::I128 => self.alias("i128"),
            T::U256 => self.alias("u256"),
            T::I256 => self.alias("i256"),
            T::Timepoint => self.alias("Timepoint"),
            T::Duration => self.alias("Duration"),
            T::String | T::Symbol => "string".into(),
            T::Address => self.alias("Address"),
            T::Bytes | T::BytesN(_) => self.alias("Bytes"),
            T::Option(o) => format!("{} | null", self.ts(&o.value_type, pos)),
            T::Vec(v) => {
                let inner = self.ts(&v.element_type, pos);
                if inner.contains('|') {
                    format!("({inner})[]")
                } else {
                    format!("{inner}[]")
                }
            }
            T::Tuple(t) => {
                let inner: Vec<String> = t.value_types.iter().map(|et| self.ts(et, pos)).collect();
                format!("[{}]", inner.join(", "))
            }
            // Only symbol/string-keyed maps round-trip through JSON objects.
            T::Map(m) => format!("Record<string, {}>", self.ts(&m.value_type, pos)),
            // A `Result` return means the call traps on `Err` (a 400 from the
            // API), so a successful result is always the `Ok` value.
            T::Result(r) => match pos {
                Pos::Ret => self.ts(&r.ok_type, pos),
                Pos::Arg => "never".into(),
            },
            // Not encodable as arguments — `never` keeps the type-level story
            // in sync with the 400 the server would return.
            T::Val | T::Error => match pos {
                Pos::Ret => "unknown".into(),
                Pos::Arg => "never".into(),
            },
            T::MuxedAddress => match pos {
                Pos::Ret => "string".into(),
                Pos::Arg => "never".into(),
            },
            T::Udt(u) => {
                let name = u.name.to_utf8_string_lossy();
                if self.has_udt(&name) {
                    name
                } else {
                    // The spec referenced a type it doesn't define.
                    "unknown".into()
                }
            }
        }
    }

    /// The scalar aliases the rest of the file referenced, in a stable order.
    fn render_prelude(&self) -> String {
        let mut out = String::new();
        for (name, def, doc) in ALIASES {
            if self.used.contains(name) {
                let _ = write!(out, "\n/** {doc} */\nexport type {name} = {def};\n");
            }
        }
        out
    }

    /// One TypeScript type per user-defined type, in spec order.
    fn render_udts(&mut self) -> String {
        let mut out = String::new();
        // Copy of the reference, so iterating the spec doesn't hold `self`.
        let spec = self.spec;

        for s in &spec.structs {
            out.push('\n');
            if is_tuple_struct(s) {
                let tys: Vec<String> = s.fields.iter().map(|f| self.ts(&f.ty, Pos::Ret)).collect();
                let _ = writeln!(out, "export type {} = [{}];", s.name, tys.join(", "));
            } else {
                let _ = writeln!(out, "export interface {} {{", s.name);
                for f in &s.fields {
                    let ty = self.ts(&f.ty, Pos::Ret);
                    let _ = writeln!(out, "  {}: {};", ts_key(&f.name), ty);
                }
                out.push_str("}\n");
            }
        }

        for e in &spec.enums {
            let cases: Vec<String> = e
                .cases
                .iter()
                .map(|(name, value)| format!("{name} = {value}"))
                .collect();
            let names: Vec<String> = e
                .cases
                .iter()
                .map(|(name, _)| format!("{:?}", name))
                .collect();
            let _ = write!(
                out,
                "\n/** Unit enum ({}). Values decode to the case name. */\nexport type {} = {} | number;\n",
                cases.join(", "),
                e.name,
                names.join(" | "),
            );
        }

        for u in &spec.unions {
            let mut cases = Vec::with_capacity(u.cases.len());
            for c in &u.cases {
                if c.tys.is_empty() {
                    cases.push(format!("{:?}", c.name));
                } else {
                    let tys: Vec<String> = c.tys.iter().map(|ty| self.ts(ty, Pos::Ret)).collect();
                    cases.push(format!("{{ {}: [{}] }}", ts_key(&c.name), tys.join(", ")));
                }
            }
            let _ = write!(
                out,
                "\nexport type {} =\n  | {};\n",
                u.name,
                cases.join("\n  | "),
            );
        }

        out
    }

    /// One typed method per contract function.
    fn render_methods(&mut self) -> String {
        let mut out = String::new();
        let spec = self.spec;
        for f in &spec.functions {
            out.push('\n');
            out.push_str(&self.render_method(f));
        }
        out
    }

    fn render_method(&mut self, f: &FunctionSpec) -> String {
        let mut out = String::new();

        if !f.doc.trim().is_empty() {
            out.push_str("  /**\n");
            for line in f.doc.trim().lines() {
                // A `*/` in the doc must not terminate the comment early.
                let _ = writeln!(out, "   * {}", line.replace("*/", "*\\/"));
            }
            out.push_str("   */\n");
        }

        let ret = match f.output_tys.first() {
            Some(ty) => self.ts(ty, Pos::Ret),
            None => "null".into(),
        };

        // `constructor` is special in a TS class; a computed name sidesteps it
        // (and any name that isn't a valid identifier).
        let method = if is_ts_ident(&f.name) && f.name != "constructor" {
            f.name.clone()
        } else {
            format!("[{:?}]", f.name)
        };

        if f.inputs.is_empty() {
            let _ = writeln!(
                out,
                "  {method}(opts?: CallOptions): Promise<{ret}> {{\n    \
                 return this.invoke({:?}, {{}}, opts) as Promise<{ret}>;\n  }}",
                f.name,
            );
        } else {
            let params: Vec<String> = f
                .inputs
                .iter()
                .map(|i| {
                    let ty = self.ts(&i.ty, Pos::Arg);
                    format!("{}: {}", ts_key(&i.name), ty)
                })
                .collect();
            let _ = writeln!(
                out,
                "  {method}(args: {{ {} }}, opts?: CallOptions): Promise<{ret}> {{\n    \
                 return this.invoke({:?}, args, opts) as Promise<{ret}>;\n  }}",
                params.join("; "),
                f.name,
            );
        }
        out
    }
}

// ── Python codegen ────────────────────────────────────────────────────────────

/// Generate a self-contained typed Python client (Python 3.10+, dataclasses,
/// stdlib `urllib.request` only) for `contract_id` from its on-chain interface.
pub fn python_client(contract_id: &str, spec: &ContractSpec) -> String {
    let mut out = String::new();
    let _ = write!(
        out,
        "\
# Typed client for the Soroban contract
#   {contract_id}
#
# Generated by Lumenqraph from the contract's on-chain interface.
# Zero dependencies: uses only Python 3.10+ stdlib (dataclasses, urllib).
#
# Regenerate any time from `GET /contracts/{contract_id}/sdk?lang=python`.

from __future__ import annotations

import json
import urllib.request
from dataclasses import dataclass
from typing import Any, Optional, Union

ADDRESS = str  # Stellar G… / C… strkey
BYTES = str    # hex-encoded bytes
INT = Union[int, str]  # large integers as decimal strings

"
    );

    // Emit dataclass per struct
    for s in &spec.structs {
        out.push('\n');
        let _ = writeln!(out, "@dataclass");
        let _ = writeln!(out, "class {}:", s.name);
        if s.fields.is_empty() {
            out.push_str("    pass\n");
        } else {
            for f in &s.fields {
                let ty = py_type(&f.ty);
                let _ = writeln!(out, "    {}: {}", py_ident(&f.name), ty);
            }
        }
    }

    // Emit simple str enums
    for e in &spec.enums {
        let cases: Vec<String> = e.cases.iter().map(|(n, _)| format!("    {} = {:?}", n, n)).collect();
        out.push('\n');
        let _ = writeln!(out, "class {}:", e.name);
        if cases.is_empty() {
            out.push_str("    pass\n");
        } else {
            for c in &cases {
                out.push_str(c);
                out.push('\n');
            }
        }
    }

    // Emit ContractClient class
    let _ = write!(
        out,
        "
class ContractClient:
    CONTRACT_ID = {contract_id:?}

    def __init__(self, base_url: str, api_key: Optional[str] = None) -> None:
        self._base_url = base_url.rstrip(\"/\")
        self._api_key = api_key

    def _call(self, function: str, args: dict[str, Any]) -> Any:
        url = f\"{{self._base_url}}/contracts/{{self.CONTRACT_ID}}/call\"
        body = json.dumps({{\"function\": function, \"args\": args}}).encode()
        req = urllib.request.Request(
            url,
            data=body,
            headers={{\"Content-Type\": \"application/json\"}},
        )
        if self._api_key:
            req.add_header(\"x-api-key\", self._api_key)
        with urllib.request.urlopen(req) as resp:
            data = json.loads(resp.read())
        return data.get(\"result\", {{}}). get(\"value\")
"
    );

    // Emit one method per function
    for f in &spec.functions {
        out.push('\n');
        let ret = py_return_type(f.output_tys.first());
        if f.inputs.is_empty() {
            let _ = writeln!(
                out,
                "    def {}(self) -> {ret}:",
                py_ident(&f.name)
            );
        } else {
            let params: Vec<String> = f
                .inputs
                .iter()
                .map(|i| format!("{}: {}", py_ident(&i.name), py_type(&i.ty)))
                .collect();
            let _ = writeln!(
                out,
                "    def {}(self, {}) -> {ret}:",
                py_ident(&f.name),
                params.join(", ")
            );
        }
        if !f.doc.trim().is_empty() {
            let _ = writeln!(out, "        \"\"\"{}\"\"\"", f.doc.trim().replace("\"\"\"", "\\\"\\\"\\\""));
        }
        if f.inputs.is_empty() {
            let _ = writeln!(out, "        return self._call({:?}, {{}})", f.name);
        } else {
            let arg_pairs: Vec<String> = f
                .inputs
                .iter()
                .map(|i| format!("{:?}: {}", i.name, py_ident(&i.name)))
                .collect();
            let _ = writeln!(
                out,
                "        return self._call({:?}, {{{}}})",
                f.name,
                arg_pairs.join(", ")
            );
        }
    }

    out
}

fn py_type(ty: &ScSpecTypeDef) -> String {
    use ScSpecTypeDef as T;
    match ty {
        T::Bool => "bool".into(),
        T::Void => "None".into(),
        T::U32 | T::I32 => "int".into(),
        T::U64 | T::I64 | T::U128 | T::I128 | T::U256 | T::I256 | T::Timepoint | T::Duration => {
            "INT".into()
        }
        T::String | T::Symbol => "str".into(),
        T::Address => "ADDRESS".into(),
        T::Bytes | T::BytesN(_) => "BYTES".into(),
        T::Option(o) => format!("Optional[{}]", py_type(&o.value_type)),
        T::Vec(v) => format!("list[{}]", py_type(&v.element_type)),
        T::Tuple(t) => {
            let inner: Vec<String> = t.value_types.iter().map(py_type).collect();
            format!("tuple[{}]", inner.join(", "))
        }
        T::Map(m) => format!("dict[str, {}]", py_type(&m.value_type)),
        T::Result(r) => py_type(&r.ok_type),
        T::Val | T::Error | T::MuxedAddress => "Any".into(),
        T::Udt(u) => u.name.to_utf8_string_lossy(),
    }
}

fn py_return_type(ty: Option<&ScSpecTypeDef>) -> String {
    ty.map_or_else(|| "None".into(), py_type)
}

fn py_ident(name: &str) -> String {
    // Python keywords that must be escaped
    match name {
        "from" | "class" | "import" | "return" | "def" | "lambda" | "pass" | "in" | "is"
        | "not" | "and" | "or" | "else" | "if" | "for" | "while" | "with" | "yield"
        | "raise" | "try" | "except" | "finally" | "del" | "global" | "nonlocal"
        | "assert" | "break" | "continue" | "as" | "type" => format!("{name}_"),
        _ => name.replace('-', "_"),
    }
}

// ── Rust codegen ──────────────────────────────────────────────────────────────

/// Generate a self-contained typed Rust client (`reqwest` + `serde`) for
/// `contract_id` from its on-chain interface.
pub fn rust_client(contract_id: &str, spec: &ContractSpec) -> String {
    let mut out = String::new();
    let _ = write!(
        out,
        "\
//! Typed client for the Soroban contract
//!   {contract_id}
//!
//! Generated by Lumenqraph from the contract's on-chain interface.
//! Depends on `reqwest` (with `json` feature) and `serde` / `serde_json`.
//!
//! Regenerate any time from `GET /contracts/{contract_id}/sdk?lang=rust`.

use serde::{{Deserialize, Serialize}};

pub const CONTRACT_ID: &str = {contract_id:?};

"
    );

    // Emit one struct per UDT struct
    for s in &spec.structs {
        let _ = writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]");
        let _ = writeln!(out, "pub struct {} {{", s.name);
        for f in &s.fields {
            let ty = rust_type(&f.ty);
            let _ = writeln!(out, "    pub {}: {ty},", rust_ident(&f.name));
        }
        out.push_str("}\n\n");
    }

    // Emit one enum per UDT enum
    for e in &spec.enums {
        let _ = writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]");
        let _ = writeln!(out, "pub enum {} {{", e.name);
        for (name, _) in &e.cases {
            let _ = writeln!(out, "    {name},");
        }
        out.push_str("}\n\n");
    }

    // Emit one enum per UDT union
    for u in &spec.unions {
        let _ = writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]");
        let _ = writeln!(out, "#[serde(untagged)]");
        let _ = writeln!(out, "pub enum {} {{", u.name);
        for c in &u.cases {
            if c.tys.is_empty() {
                let _ = writeln!(out, "    {},", c.name);
            } else if c.tys.len() == 1 {
                let ty = rust_type(&c.tys[0]);
                let _ = writeln!(out, "    {}({}),", c.name, ty);
            } else {
                let tys: Vec<String> = c.tys.iter().map(rust_type).collect();
                let _ = writeln!(out, "    {}({}),", c.name, tys.join(", "));
            }
        }
        out.push_str("}\n\n");
    }

    let _ = write!(
        out,
        "\
#[derive(Debug, Clone, Deserialize)]
struct CallResponse {{
    result: Option<ResultValue>,
}}

#[derive(Debug, Clone, Deserialize)]
struct ResultValue {{
    value: Option<serde_json::Value>,
}}

#[derive(Debug, Clone)]
pub struct ContractClient {{
    base_url: String,
    api_key: Option<String>,
    client: reqwest::Client,
}}

impl ContractClient {{
    pub fn new(base_url: impl Into<String>) -> Self {{
        Self {{
            base_url: base_url.into().trim_end_matches('/').to_string(),
            api_key: None,
            client: reqwest::Client::new(),
        }}
    }}

    pub fn with_api_key(mut self, key: impl Into<String>) -> Self {{
        self.api_key = Some(key.into());
        self
    }}

    async fn invoke(
        &self,
        function: &str,
        args: serde_json::Value,
    ) -> Result<Option<serde_json::Value>, reqwest::Error> {{
        let url = format!(\"{{base}}/contracts/{{cid}}/call\",
            base = self.base_url,
            cid = CONTRACT_ID);
        let body = serde_json::json!({{\"function\": function, \"args\": args}});
        let mut req = self.client.post(&url).json(&body);
        if let Some(key) = &self.api_key {{
            req = req.header(\"x-api-key\", key);
        }}
        let resp: CallResponse = req.send().await?.json().await?;
        Ok(resp.result.and_then(|r| r.value))
    }}
"
    );

    // Emit one method per function
    for f in &spec.functions {
        out.push('\n');
        if !f.doc.trim().is_empty() {
            for line in f.doc.trim().lines() {
                let _ = writeln!(out, "    /// {}", line.replace("*/", "* /"));
            }
        }
        let ret = rust_return_type(f.output_tys.first());
        if f.inputs.is_empty() {
            let _ = writeln!(
                out,
                "    pub async fn {}(&self) -> Result<{ret}, reqwest::Error> {{",
                rust_ident(&f.name)
            );
            let _ = writeln!(
                out,
                "        let v = self.invoke({:?}, serde_json::json!({{}})).await?;",
                f.name
            );
        } else {
            let params: Vec<String> = f
                .inputs
                .iter()
                .map(|i| {
                    let ty = rust_type(&i.ty);
                    format!("{}: {ty}", rust_ident(&i.name))
                })
                .collect();
            let _ = writeln!(
                out,
                "    pub async fn {}(&self, {}) -> Result<{ret}, reqwest::Error> {{",
                rust_ident(&f.name),
                params.join(", ")
            );
            let arg_pairs: Vec<String> = f
                .inputs
                .iter()
                .map(|i| format!("{:?}: {}", i.name, rust_ident(&i.name)))
                .collect();
            let _ = writeln!(
                out,
                "        let v = self.invoke({:?}, serde_json::json!({{{}}})).await?;",
                f.name,
                arg_pairs.join(", ")
            );
        }
        if f.output_tys.is_empty() {
            out.push_str("        let _ = v;\n        Ok(())\n    }\n");
        } else {
            out.push_str("        Ok(v)\n    }\n");
        }
    }

    out.push_str("}\n");
    out
}

fn rust_type(ty: &ScSpecTypeDef) -> String {
    use ScSpecTypeDef as T;
    match ty {
        T::Bool => "bool".into(),
        T::Void => "()".into(),
        T::U32 => "u32".into(),
        T::I32 => "i32".into(),
        T::U64 | T::Timepoint => "u64".into(),
        T::I64 | T::Duration => "i64".into(),
        T::U128 | T::U256 => "String".into(), // decimal strings for big ints
        T::I128 | T::I256 => "String".into(),
        T::String | T::Symbol => "String".into(),
        T::Address => "String".into(), // strkey
        T::Bytes | T::BytesN(_) => "String".into(), // hex
        T::Option(o) => format!("Option<{}>", rust_type(&o.value_type)),
        T::Vec(v) => format!("Vec<{}>", rust_type(&v.element_type)),
        T::Tuple(t) => {
            let inner: Vec<String> = t.value_types.iter().map(rust_type).collect();
            format!("({})", inner.join(", "))
        }
        T::Map(m) => format!(
            "std::collections::HashMap<String, {}>",
            rust_type(&m.value_type)
        ),
        T::Result(r) => rust_type(&r.ok_type),
        T::Val | T::Error | T::MuxedAddress => "serde_json::Value".into(),
        T::Udt(u) => u.name.to_utf8_string_lossy(),
    }
}

fn rust_return_type(ty: Option<&ScSpecTypeDef>) -> String {
    ty.map_or_else(|| "()".into(), rust_type)
}

fn rust_ident(name: &str) -> String {
    // Rust keywords
    match name {
        "type" | "self" | "fn" | "let" | "mut" | "use" | "mod" | "pub" | "impl" | "struct"
        | "enum" | "trait" | "match" | "if" | "else" | "for" | "while" | "loop" | "return"
        | "break" | "continue" | "where" | "as" | "in" | "ref" | "move" | "async" | "await"
        | "dyn" | "unsafe" | "extern" | "crate" | "super" | "static" | "const" | "box"
        | "true" | "false" => format!("r#{name}"),
        _ => name.replace('-', "_"),
    }
}

// ── Shared helpers ────────────────────────────────────────────────────────────

/// soroban-sdk names tuple-struct fields "0", "1", … — those encode (and
/// decode) positionally, so they become a TS tuple type rather than an object.
fn is_tuple_struct(s: &UdtStruct) -> bool {
    !s.fields.is_empty()
        && s.fields
            .iter()
            .all(|f| f.name.chars().all(|c| c.is_ascii_digit()))
}

fn is_ts_ident(s: &str) -> bool {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' || c == '$' => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
}

/// A field/parameter name as a TS object key, quoted only when it has to be.
fn ts_key(name: &str) -> String {
    if is_ts_ident(name) {
        name.to_string()
    } else {
        format!("{name:?}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use stellar_xdr::curr::{
        Limits, ScSpecEntry, ScSpecFunctionInputV0, ScSpecFunctionV0, ScSpecTypeDef,
        ScSpecTypeOption, ScSpecTypeUdt, ScSpecTypeVec, ScSpecUdtEnumCaseV0, ScSpecUdtEnumV0,
        ScSpecUdtStructFieldV0, ScSpecUdtStructV0, ScSpecUdtUnionCaseTupleV0, ScSpecUdtUnionCaseV0,
        ScSpecUdtUnionCaseVoidV0, ScSpecUdtUnionV0, ScSymbol, WriteXdr,
    };

    const C: &str = "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSC4";

    fn udt(name: &str) -> ScSpecTypeDef {
        ScSpecTypeDef::Udt(ScSpecTypeUdt {
            name: name.try_into().unwrap(),
        })
    }

    fn function(
        name: &str,
        doc: &str,
        inputs: Vec<(&str, ScSpecTypeDef)>,
        output: Option<ScSpecTypeDef>,
    ) -> ScSpecEntry {
        ScSpecEntry::FunctionV0(ScSpecFunctionV0 {
            doc: doc.try_into().unwrap(),
            name: ScSymbol(name.try_into().unwrap()),
            inputs: inputs
                .into_iter()
                .map(|(n, ty)| ScSpecFunctionInputV0 {
                    doc: "".try_into().unwrap(),
                    name: n.try_into().unwrap(),
                    type_: ty,
                })
                .collect::<Vec<_>>()
                .try_into()
                .unwrap(),
            outputs: output.into_iter().collect::<Vec<_>>().try_into().unwrap(),
        })
    }

    fn spec(entries: &[ScSpecEntry]) -> ContractSpec {
        let mut body = Vec::new();
        for e in entries {
            body.extend(e.to_xdr(Limits::none()).unwrap());
        }
        ContractSpec::from_spec_xdr(&body).expect("spec should parse")
    }

    fn full_spec() -> ContractSpec {
        // struct Position { borrower: Address, debt: i128 }
        let position = ScSpecEntry::UdtStructV0(ScSpecUdtStructV0 {
            doc: "".try_into().unwrap(),
            lib: "".try_into().unwrap(),
            name: "Position".try_into().unwrap(),
            fields: vec![
                ScSpecUdtStructFieldV0 {
                    doc: "".try_into().unwrap(),
                    name: "borrower".try_into().unwrap(),
                    type_: ScSpecTypeDef::Address,
                },
                ScSpecUdtStructFieldV0 {
                    doc: "".try_into().unwrap(),
                    name: "debt".try_into().unwrap(),
                    type_: ScSpecTypeDef::I128,
                },
            ]
            .try_into()
            .unwrap(),
        });
        // enum Status { Active = 0, Filled = 7 }
        let status = ScSpecEntry::UdtEnumV0(ScSpecUdtEnumV0 {
            doc: "".try_into().unwrap(),
            lib: "".try_into().unwrap(),
            name: "Status".try_into().unwrap(),
            cases: vec![
                ScSpecUdtEnumCaseV0 {
                    doc: "".try_into().unwrap(),
                    name: "Active".try_into().unwrap(),
                    value: 0,
                },
                ScSpecUdtEnumCaseV0 {
                    doc: "".try_into().unwrap(),
                    name: "Filled".try_into().unwrap(),
                    value: 7,
                },
            ]
            .try_into()
            .unwrap(),
        });
        // union Action { Cancel, Bid(i128) }
        let action = ScSpecEntry::UdtUnionV0(ScSpecUdtUnionV0 {
            doc: "".try_into().unwrap(),
            lib: "".try_into().unwrap(),
            name: "Action".try_into().unwrap(),
            cases: vec![
                ScSpecUdtUnionCaseV0::VoidV0(ScSpecUdtUnionCaseVoidV0 {
                    doc: "".try_into().unwrap(),
                    name: "Cancel".try_into().unwrap(),
                }),
                ScSpecUdtUnionCaseV0::TupleV0(ScSpecUdtUnionCaseTupleV0 {
                    doc: "".try_into().unwrap(),
                    name: "Bid".try_into().unwrap(),
                    type_: vec![ScSpecTypeDef::I128].try_into().unwrap(),
                }),
            ]
            .try_into()
            .unwrap(),
        });

        let vec_of_addr = ScSpecTypeDef::Vec(Box::new(ScSpecTypeVec {
            element_type: Box::new(ScSpecTypeDef::Address),
        }));
        let opt_u32 = ScSpecTypeDef::Option(Box::new(ScSpecTypeOption {
            value_type: Box::new(ScSpecTypeDef::U32),
        }));

        spec(&[
            position,
            status,
            action,
            function(
                "get_position",
                "Look up a borrower's position.",
                vec![("borrower", ScSpecTypeDef::Address)],
                Some(udt("Position")),
            ),
            function(
                "act",
                "",
                vec![("action", udt("Action")), ("hint", opt_u32)],
                Some(udt("Status")),
            ),
            function("holders", "", vec![], Some(vec_of_addr)),
            function("reset", "", vec![], None),
        ])
    }

    #[test]
    fn generates_types_for_every_udt_shape() {
        let ts = typescript_client(C, &full_spec());
        assert!(ts.contains("export interface Position {\n  borrower: Address;\n  debt: i128;\n}"));
        assert!(ts.contains(r#"export type Status = "Active" | "Filled" | number;"#));
        assert!(ts.contains("export type Action =\n  | \"Cancel\"\n  | { Bid: [i128] };"));
    }

    #[test]
    fn generates_typed_methods() {
        let ts = typescript_client(C, &full_spec());
        assert!(ts.contains("Look up a borrower's position."));
        assert!(ts.contains(
            "get_position(args: { borrower: Address }, opts?: CallOptions): Promise<Position>"
        ));
        assert!(ts.contains(
            "act(args: { action: Action; hint: number | null }, opts?: CallOptions): Promise<Status>"
        ));
        // Zero-arg function takes only options; void function resolves null.
        assert!(ts.contains("holders(opts?: CallOptions): Promise<Address[]>"));
        assert!(ts.contains("reset(opts?: CallOptions): Promise<null>"));
        assert!(ts.contains(C));
    }

    #[test]
    fn emits_only_the_aliases_the_interface_uses() {
        let ts = typescript_client(C, &full_spec());
        assert!(ts.contains("export type Address = string;"));
        assert!(ts.contains("export type i128 = number | string;"));
        // Nothing in the interface touches these.
        assert!(!ts.contains("export type u256"));
        assert!(!ts.contains("export type Duration"));
    }

    #[test]
    fn tuple_structs_become_tuple_types() {
        let pair = ScSpecEntry::UdtStructV0(ScSpecUdtStructV0 {
            doc: "".try_into().unwrap(),
            lib: "".try_into().unwrap(),
            name: "Pair".try_into().unwrap(),
            fields: vec![
                ScSpecUdtStructFieldV0 {
                    doc: "".try_into().unwrap(),
                    name: "0".try_into().unwrap(),
                    type_: ScSpecTypeDef::Address,
                },
                ScSpecUdtStructFieldV0 {
                    doc: "".try_into().unwrap(),
                    name: "1".try_into().unwrap(),
                    type_: ScSpecTypeDef::U32,
                },
            ]
            .try_into()
            .unwrap(),
        });
        let ts = typescript_client(C, &spec(&[pair]));
        assert!(ts.contains("export type Pair = [Address, number];"));
    }

    #[test]
    fn awkward_function_names_get_computed_keys() {
        let s = spec(&[function(
            "constructor",
            "",
            vec![],
            Some(ScSpecTypeDef::U32),
        )]);
        let ts = typescript_client(C, &s);
        assert!(ts.contains(r#"["constructor"](opts?: CallOptions): Promise<number>"#));
    }

    #[test]
    fn output_is_deterministic() {
        let ts = typescript_client(C, &full_spec());
        assert_eq!(ts, typescript_client(C, &full_spec()));
        // Dump for an external `tsc` compile check during development.
        if let Ok(path) = std::env::var("CODEGEN_DUMP") {
            std::fs::write(path, &ts).unwrap();
        }
    }

    #[test]
    fn generates_valid_prelude_with_contract_id() {
        let ts = typescript_client(
            C,
            &spec(&[function("balance", "", vec![], Some(ScSpecTypeDef::I128))]),
        );
        assert!(ts.starts_with("// Typed client for the Soroban contract"));
        assert!(ts.contains(C));
        assert!(ts.contains("export class ContractClient"));
        assert!(ts.contains("constructor(config: { baseUrl: string })"));
    }

    #[test]
    fn empty_spec_generates_valid_client() {
        // A minimal contract with no functions should still generate valid code
        let minimal = spec(&[]);
        let ts = typescript_client(C, &minimal);
        assert!(ts.contains("export class ContractClient"));
        assert!(ts.contains("constructor(config: { baseUrl: string })"));
    }

    #[test]
    fn handles_reserved_keywords_as_function_names() {
        let reserved = spec(&[
            function("class", "", vec![], Some(ScSpecTypeDef::U32)),
            function("interface", "", vec![], Some(ScSpecTypeDef::U32)),
            function("type", "", vec![], Some(ScSpecTypeDef::U32)),
        ]);
        let ts = typescript_client(C, &reserved);
        // Reserved keywords should be quoted in computed properties
        assert!(ts.contains(r#"["class"]"#) || ts.contains("class"));
        assert!(ts.contains(r#"["interface"]"#) || ts.contains("interface"));
        assert!(ts.contains(r#"["type"]"#) || ts.contains("type"));
    }

    #[test]
    fn handles_all_scalar_types() {
        let scalars = spec(&[
            function("f_u32", "", vec![], Some(ScSpecTypeDef::U32)),
            function("f_i32", "", vec![], Some(ScSpecTypeDef::I32)),
            function("f_u64", "", vec![], Some(ScSpecTypeDef::U64)),
            function("f_i64", "", vec![], Some(ScSpecTypeDef::I64)),
            function("f_u128", "", vec![], Some(ScSpecTypeDef::U128)),
            function("f_i128", "", vec![], Some(ScSpecTypeDef::I128)),
            function("f_bool", "", vec![], Some(ScSpecTypeDef::Bool)),
            function("f_symbol", "", vec![], Some(ScSpecTypeDef::Symbol)),
            function("f_bytes", "", vec![], Some(ScSpecTypeDef::Bytes)),
            function("f_timepoint", "", vec![], Some(ScSpecTypeDef::Timepoint)),
            function("f_duration", "", vec![], Some(ScSpecTypeDef::Duration)),
        ]);
        let ts = typescript_client(C, &scalars);
        assert!(ts.contains("f_u32(opts?: CallOptions): Promise<number>"));
        assert!(ts.contains("f_i32(opts?: CallOptions): Promise<number>"));
        assert!(ts.contains("f_u64(opts?: CallOptions): Promise<number | string>"));
        assert!(ts.contains("f_bool(opts?: CallOptions): Promise<boolean>"));
    }

    #[test]
    fn handles_container_types() {
        let vec_of_u32 = ScSpecTypeDef::Vec(Box::new(ScSpecTypeVec {
            element_type: Box::new(ScSpecTypeDef::U32),
        }));
        let map_of_str_to_i128 = ScSpecTypeDef::Map(Box::new(stellar_xdr::curr::ScSpecTypeMap {
            key_type: Box::new(ScSpecTypeDef::Symbol),
            value_type: Box::new(ScSpecTypeDef::I128),
        }));

        let containers = spec(&[
            function("vecs", "", vec![], Some(vec_of_u32)),
            function("maps", "", vec![], Some(map_of_str_to_i128)),
        ]);
        let ts = typescript_client(C, &containers);
        assert!(ts.contains("vecs(opts?: CallOptions): Promise<number[]>"));
        assert!(ts.contains("maps(opts?: CallOptions): Promise<Record<string, i128>>"));
    }

    #[test]
    fn handles_nested_containers() {
        let vec_of_vec = ScSpecTypeDef::Vec(Box::new(ScSpecTypeVec {
            element_type: Box::new(ScSpecTypeDef::Vec(Box::new(ScSpecTypeVec {
                element_type: Box::new(ScSpecTypeDef::U32),
            }))),
        }));

        let nested = spec(&[function("nested", "", vec![], Some(vec_of_vec))]);
        let ts = typescript_client(C, &nested);
        assert!(ts.contains("number[][]"));
    }

    #[test]
    fn full_spec_generates_complete_client() {
        let ts = typescript_client(C, &full_spec());

        // Check structure
        assert!(ts.contains("export class ContractClient"));
        assert!(ts.contains("export interface Position"));
        assert!(ts.contains("export type Status"));
        assert!(ts.contains("export type Action"));

        // Check methods
        assert!(ts.contains("get_position"));
        assert!(ts.contains("act"));
        assert!(ts.contains("holders"));
        assert!(ts.contains("reset"));

        // Check type aliases
        assert!(ts.contains("export type Address"));
        assert!(ts.contains("export type i128"));

        // Ensure it looks like valid TypeScript (has imports, exports, class definition)
        assert!(ts.contains("export"));
        assert!(ts.contains("async"));
        assert!(ts.contains("Promise"));
    }

    #[test]
    fn emits_correct_numeric_aliases_for_integer_types() {
        let ints = spec(&[
            function("small", "", vec![], Some(ScSpecTypeDef::U32)),
            function("big", "", vec![], Some(ScSpecTypeDef::U128)),
        ]);
        let ts = typescript_client(C, &ints);
        // u32 should be number, u128 should be number | string
        assert!(ts.contains("export type u128 = number | string;"));
        assert!(!ts.contains("export type u32 = "));
    }

    #[test]
    fn tuple_struct_with_single_field() {
        let single_field_tuple = ScSpecEntry::UdtStructV0(ScSpecUdtStructV0 {
            doc: "".try_into().unwrap(),
            lib: "".try_into().unwrap(),
            name: "Single".try_into().unwrap(),
            fields: vec![ScSpecUdtStructFieldV0 {
                doc: "".try_into().unwrap(),
                name: "0".try_into().unwrap(),
                type_: ScSpecTypeDef::Address,
            }]
            .try_into()
            .unwrap(),
        });
        let ts = typescript_client(C, &spec(&[single_field_tuple]));
        assert!(ts.contains("export type Single = [Address];"));
    }

    #[test]
    fn struct_with_many_fields() {
        let many_fields = ScSpecEntry::UdtStructV0(ScSpecUdtStructV0 {
            doc: "".try_into().unwrap(),
            lib: "".try_into().unwrap(),
            name: "LargeStruct".try_into().unwrap(),
            fields: vec![
                ScSpecUdtStructFieldV0 {
                    doc: "".try_into().unwrap(),
                    name: "field_a".try_into().unwrap(),
                    type_: ScSpecTypeDef::Address,
                },
                ScSpecUdtStructFieldV0 {
                    doc: "".try_into().unwrap(),
                    name: "field_b".try_into().unwrap(),
                    type_: ScSpecTypeDef::I128,
                },
                ScSpecUdtStructFieldV0 {
                    doc: "".try_into().unwrap(),
                    name: "field_c".try_into().unwrap(),
                    type_: ScSpecTypeDef::Bool,
                },
                ScSpecUdtStructFieldV0 {
                    doc: "".try_into().unwrap(),
                    name: "field_d".try_into().unwrap(),
                    type_: ScSpecTypeDef::U32,
                },
            ]
            .try_into()
            .unwrap(),
        });
        let ts = typescript_client(C, &spec(&[many_fields]));
        assert!(ts.contains("export interface LargeStruct {"));
        assert!(ts.contains("field_a: Address;"));
        assert!(ts.contains("field_b: i128;"));
        assert!(ts.contains("field_c: boolean;"));
        assert!(ts.contains("field_d: number;"));
    }

    #[test]
    fn union_with_multiple_cases_and_payloads() {
        use stellar_xdr::curr::{
            ScSpecUdtUnionCaseTupleV0, ScSpecUdtUnionCaseV0, ScSpecUdtUnionV0,
        };

        let complex_union = ScSpecEntry::UdtUnionV0(ScSpecUdtUnionV0 {
            doc: "".try_into().unwrap(),
            lib: "".try_into().unwrap(),
            name: "ComplexUnion".try_into().unwrap(),
            cases: vec![
                ScSpecUdtUnionCaseV0::VoidV0(ScSpecUdtUnionCaseVoidV0 {
                    doc: "".try_into().unwrap(),
                    name: "Void".try_into().unwrap(),
                }),
                ScSpecUdtUnionCaseV0::TupleV0(ScSpecUdtUnionCaseTupleV0 {
                    doc: "".try_into().unwrap(),
                    name: "Single".try_into().unwrap(),
                    type_: vec![ScSpecTypeDef::I128].try_into().unwrap(),
                }),
                ScSpecUdtUnionCaseV0::TupleV0(ScSpecUdtUnionCaseTupleV0 {
                    doc: "".try_into().unwrap(),
                    name: "Pair".try_into().unwrap(),
                    type_: vec![ScSpecTypeDef::Address, ScSpecTypeDef::U32]
                        .try_into()
                        .unwrap(),
                }),
            ]
            .try_into()
            .unwrap(),
        });
        let ts = typescript_client(C, &spec(&[complex_union]));
        assert!(ts.contains("export type ComplexUnion ="));
        assert!(ts.contains(r#""Void""#));
        assert!(ts.contains("Single"));
        assert!(ts.contains("Pair"));
    }

    #[test]
    fn function_with_complex_args() {
        let complex_args = spec(&[function(
            "complex",
            "",
            vec![
                ("addr", ScSpecTypeDef::Address),
                ("count", ScSpecTypeDef::U32),
                ("enabled", ScSpecTypeDef::Bool),
                ("data", ScSpecTypeDef::Bytes),
            ],
            Some(ScSpecTypeDef::U64),
        )]);
        let ts = typescript_client(C, &complex_args);
        assert!(ts.contains("complex(args: {"));
        assert!(ts.contains("addr: Address;"));
        assert!(ts.contains("count: number;"));
        assert!(ts.contains("enabled: boolean;"));
        assert!(ts.contains("data: Bytes;"));
    }

    #[test]
    fn codegen_includes_call_options_interface() {
        let ts = typescript_client(C, &full_spec());
        assert!(ts.contains("interface CallOptions"));
        assert!(ts.contains("timeout?:"));
    }

    #[test]
    fn codegen_includes_helper_functions() {
        let ts = typescript_client(C, &full_spec());
        // Should include helper for making POST requests to the contract
        assert!(ts.contains("async") || ts.contains("await"));
        assert!(ts.contains("/contracts/") || ts.contains("call"));
    }

    // ── Python codegen tests ──────────────────────────────────────────────────

    #[test]
    fn python_client_contains_class_and_methods() {
        let py = python_client(C, &full_spec());
        assert!(py.contains("class ContractClient:"));
        assert!(py.contains("CONTRACT_ID ="));
        assert!(py.contains(C));
        // Methods from full_spec
        assert!(py.contains("def get_position("));
        assert!(py.contains("def act("));
        assert!(py.contains("def holders("));
        assert!(py.contains("def reset("));
    }

    #[test]
    fn python_client_emits_dataclasses_for_structs() {
        let py = python_client(C, &full_spec());
        assert!(py.contains("@dataclass"));
        assert!(py.contains("class Position:"));
        assert!(py.contains("borrower: ADDRESS"));
        assert!(py.contains("debt: INT"));
    }

    #[test]
    fn python_client_handles_keyword_names() {
        let s = spec(&[function("from", "", vec![], Some(ScSpecTypeDef::U32))]);
        let py = python_client(C, &s);
        // "from" is a Python keyword; should be escaped to "from_"
        assert!(py.contains("def from_("));
    }

    #[test]
    fn python_client_is_deterministic() {
        assert_eq!(python_client(C, &full_spec()), python_client(C, &full_spec()));
    }

    // ── Rust codegen tests ────────────────────────────────────────────────────

    #[test]
    fn rust_client_contains_struct_and_impl() {
        let rs = rust_client(C, &full_spec());
        assert!(rs.contains("pub struct ContractClient"));
        assert!(rs.contains("impl ContractClient"));
        assert!(rs.contains("pub const CONTRACT_ID:"));
        assert!(rs.contains(C));
    }

    #[test]
    fn rust_client_emits_structs_for_udts() {
        let rs = rust_client(C, &full_spec());
        assert!(rs.contains("pub struct Position {"));
        assert!(rs.contains("pub borrower: String,"));
        assert!(rs.contains("pub debt: String,"));
    }

    #[test]
    fn rust_client_emits_enums_for_udt_enums() {
        let rs = rust_client(C, &full_spec());
        assert!(rs.contains("pub enum Status {"));
        assert!(rs.contains("Active,"));
        assert!(rs.contains("Filled,"));
    }

    #[test]
    fn rust_client_emits_async_methods() {
        let rs = rust_client(C, &full_spec());
        assert!(rs.contains("pub async fn get_position("));
        assert!(rs.contains("pub async fn reset("));
    }

    #[test]
    fn rust_client_handles_keyword_names() {
        let s = spec(&[function("type", "", vec![], Some(ScSpecTypeDef::U32))]);
        let rs = rust_client(C, &s);
        // "type" is a Rust keyword; should be escaped with r#
        assert!(rs.contains("pub async fn r#type("));
    }

    #[test]
    fn rust_client_is_deterministic() {
        assert_eq!(rust_client(C, &full_spec()), rust_client(C, &full_spec()));
    }
}
