//! Typed client **codegen** from a contract's on-chain interface.
//!
//! On EVM chains, generating a typed client means hunting down an ABI file and
//! hoping it matches what's deployed. A Soroban contract *ships* its interface
//! on-chain (see [`crate::spec`]), so a typed client can be generated from the
//! chain itself, with zero configuration — and regenerated the moment the
//! upgrade watch sees the interface change.
//!
//! The generated TypeScript is self-contained (platform `fetch`, no runtime
//! dependencies) and calls the contract's view functions through Lumenqraph's
//! read layer (`POST /contracts/:id/call`). Because the read layer names UDT
//! values in results (see [`crate::read::decode_result`]), one generated type
//! per user-defined type is honest in *both* directions: what a call returns is
//! shaped exactly like what the next call accepts.
//!
//! Output is deterministic — same spec in, same source out — so it can be
//! cached, tested, and diffed across interface versions.

use std::collections::BTreeSet;
use std::fmt::Write;

use stellar_xdr::curr::ScSpecTypeDef;

use crate::spec::{ContractSpec, FunctionSpec, UdtStruct};

/// Scalar type aliases the generated code may reference: name, definition, doc.
/// Only the ones actually used by the contract's interface are emitted.
const ALIASES: &[(&str, &str, &str)] = &[
    (
        "Address",
        "string",
        "A Stellar strkey address (`G…` account or `C…` contract).",
    ),
    (
        "Bytes",
        "string",
        "Hex-encoded bytes (`0x` prefix optional on input; results are `0x`-prefixed).",
    ),
    ("u64", "number | string", INT_DOC),
    ("i64", "number | string", INT_DOC),
    ("u128", "number | string", INT_DOC),
    ("i128", "number | string", INT_DOC),
    ("u256", "number | string", INT_DOC),
    ("i256", "number | string", INT_DOC),
    (
        "Timepoint",
        "number | string",
        "Seconds since the Unix epoch; returned as a decimal string.",
    ),
    (
        "Duration",
        "number | string",
        "A span of seconds; returned as a decimal string.",
    ),
];

const INT_DOC: &str =
    "Pass a decimal string (safe at any size) or a number; returned as a decimal string.";

/// Where a type appears. Arguments are type-checked by the encoder, so types it
/// rejects become `never`; results come from the generic decoder, so the same
/// types map to what decoding actually produces.
#[derive(Clone, Copy, PartialEq)]
enum Pos {
    Arg,
    Ret,
}

/// Generate a self-contained typed TypeScript client for `contract_id` from its
/// parsed on-chain interface.
pub fn typescript_client(contract_id: &str, spec: &ContractSpec) -> String {
    let mut g = Gen {
        spec,
        used: BTreeSet::new(),
    };

    // Render the interface-dependent parts first, so the prelude can include
    // exactly the scalar aliases they turned out to use.
    let udts = g.render_udts();
    let methods = g.render_methods();
    let prelude = g.render_prelude();

    let mut out = String::new();
    let _ = write!(
        out,
        "\
// Typed client for the Soroban contract
//   {contract_id}
//
// Generated by Lumenqraph from the contract's *on-chain* interface (the
// `contractspecv0` section of its deployed WASM) — no ABI file, no config.
// Calls go through Lumenqraph's read layer, which type-checks arguments
// against the same on-chain spec before they ever reach the network.
//
// Zero dependencies: works anywhere `fetch` exists (browser, Node 18+,
// Deno, Bun).
//
//   const contract = new ContractClient({{ baseUrl: \"https://…\" }});
//
// Regenerate any time from `GET /contracts/{contract_id}/sdk?lang=ts`.
// If the contract is upgraded on-chain, Lumenqraph's upgrade watch records
// it — `GET /contracts/{contract_id}/interface/history` shows what changed.
{prelude}{udts}
export interface ClientOptions {{
  /** Lumenqraph API base URL, e.g. \"https://lumenqraph.onrender.com\". */
  baseUrl: string;
  /** API key, sent as `x-api-key` (only needed if the server requires one). */
  apiKey?: string;
  /** Override the fetch implementation (defaults to global fetch). */
  fetch?: typeof fetch;
}}

export interface CallOptions {{
  /** Optional `G…` source account for the read-only simulation. */
  sourceAccount?: string;
}}

/** Error thrown for any non-2xx API response (bad arguments, trapped call…). */
export class CallError extends Error {{
  constructor(
    message: string,
    readonly status: number,
    readonly body: unknown,
  ) {{
    super(message);
    this.name = \"CallError\";
  }}
}}

export class ContractClient {{
  /** The on-chain contract this client is bound to. */
  static readonly contractId =
    \"{contract_id}\";

  constructor(private readonly opts: ClientOptions) {{}}
{methods}
  /** POST the typed call to the API and unwrap the decoded result value. */
  private async invoke(fn: string, args: unknown, opts?: CallOptions): Promise<unknown> {{
    const doFetch = this.opts.fetch ?? globalThis.fetch;
    const base = this.opts.baseUrl.replace(/\\/+$/, \"\");
    const headers: Record<string, string> = {{ \"content-type\": \"application/json\" }};
    if (this.opts.apiKey) headers[\"x-api-key\"] = this.opts.apiKey;
    const res = await doFetch(`${{base}}/contracts/${{ContractClient.contractId}}/call`, {{
      method: \"POST\",
      headers,
      body: JSON.stringify({{ function: fn, args, source_account: opts?.sourceAccount ?? null }}),
    }});
    const text = await res.text();
    let body: unknown = null;
    try {{
      body = text ? JSON.parse(text) : null;
    }} catch {{
      body = text;
    }}
    if (!res.ok) {{
      const msg =
        (body as {{ error?: string }} | null)?.error ?? `${{res.status}} ${{res.statusText}}`;
      throw new CallError(msg, res.status, body);
    }}
    return (body as {{ result?: {{ value?: unknown }} }}).result?.value ?? null;
  }}
}}
"
    );
    out
}

struct Gen<'a> {
    spec: &'a ContractSpec,
    /// Scalar aliases referenced so far (names index into [`ALIASES`]).
    used: BTreeSet<&'static str>,
}

impl Gen<'_> {
    /// Reference a scalar alias by name, recording the use — unless the
    /// contract defines a UDT with the same name, in which case the raw type is
    /// inlined so the two can't collide.
    fn alias(&mut self, name: &'static str) -> String {
        if self.has_udt(name) {
            let (_, def, _) = ALIASES.iter().find(|(n, _, _)| *n == name).unwrap();
            return (*def).to_string();
        }
        self.used.insert(name);
        name.to_string()
    }

    fn has_udt(&self, name: &str) -> bool {
        self.spec.structs.iter().any(|s| s.name == name)
            || self.spec.unions.iter().any(|u| u.name == name)
            || self.spec.enums.iter().any(|e| e.name == name)
    }

    /// Map a spec type to TypeScript. `pos` only matters for the handful of
    /// types the encoder can't take as arguments — everything else reads and
    /// writes as the same shape (see the module docs on result relabelling).
    fn ts(&mut self, ty: &ScSpecTypeDef, pos: Pos) -> String {
        use ScSpecTypeDef as T;
        match ty {
            T::Bool => "boolean".into(),
            T::Void => "null".into(),
            T::U32 | T::I32 => "number".into(),
            T::U64 => self.alias("u64"),
            T::I64 => self.alias("i64"),
            T::U128 => self.alias("u128"),
            T::I128 => self.alias("i128"),
            T::U256 => self.alias("u256"),
            T::I256 => self.alias("i256"),
            T::Timepoint => self.alias("Timepoint"),
            T::Duration => self.alias("Duration"),
            T::String | T::Symbol => "string".into(),
            T::Address => self.alias("Address"),
            T::Bytes | T::BytesN(_) => self.alias("Bytes"),
            T::Option(o) => format!("{} | null", self.ts(&o.value_type, pos)),
            T::Vec(v) => {
                let inner = self.ts(&v.element_type, pos);
                if inner.contains('|') {
                    format!("({inner})[]")
                } else {
                    format!("{inner}[]")
                }
            }
            T::Tuple(t) => {
                let inner: Vec<String> = t.value_types.iter().map(|et| self.ts(et, pos)).collect();
                format!("[{}]", inner.join(", "))
            }
            // Only symbol/string-keyed maps round-trip through JSON objects.
            T::Map(m) => format!("Record<string, {}>", self.ts(&m.value_type, pos)),
            // A `Result` return means the call traps on `Err` (a 400 from the
            // API), so a successful result is always the `Ok` value.
            T::Result(r) => match pos {
                Pos::Ret => self.ts(&r.ok_type, pos),
                Pos::Arg => "never".into(),
            },
            // Not encodable as arguments — `never` keeps the type-level story
            // in sync with the 400 the server would return.
            T::Val | T::Error => match pos {
                Pos::Ret => "unknown".into(),
                Pos::Arg => "never".into(),
            },
            T::MuxedAddress => match pos {
                Pos::Ret => "string".into(),
                Pos::Arg => "never".into(),
            },
            T::Udt(u) => {
                let name = u.name.to_utf8_string_lossy();
                if self.has_udt(&name) {
                    name
                } else {
                    // The spec referenced a type it doesn't define.
                    "unknown".into()
                }
            }
        }
    }

    /// The scalar aliases the rest of the file referenced, in a stable order.
    fn render_prelude(&self) -> String {
        let mut out = String::new();
        for (name, def, doc) in ALIASES {
            if self.used.contains(name) {
                let _ = write!(out, "\n/** {doc} */\nexport type {name} = {def};\n");
            }
        }
        out
    }

    /// One TypeScript type per user-defined type, in spec order.
    fn render_udts(&mut self) -> String {
        let mut out = String::new();
        // Copy of the reference, so iterating the spec doesn't hold `self`.
        let spec = self.spec;

        for s in &spec.structs {
            out.push('\n');
            if is_tuple_struct(s) {
                let tys: Vec<String> = s.fields.iter().map(|f| self.ts(&f.ty, Pos::Ret)).collect();
                let _ = writeln!(out, "export type {} = [{}];", s.name, tys.join(", "));
            } else {
                let _ = writeln!(out, "export interface {} {{", s.name);
                for f in &s.fields {
                    let ty = self.ts(&f.ty, Pos::Ret);
                    let _ = writeln!(out, "  {}: {};", ts_key(&f.name), ty);
                }
                out.push_str("}\n");
            }
        }

        for e in &spec.enums {
            let cases: Vec<String> = e
                .cases
                .iter()
                .map(|(name, value)| format!("{name} = {value}"))
                .collect();
            let names: Vec<String> = e
                .cases
                .iter()
                .map(|(name, _)| format!("{:?}", name))
                .collect();
            let _ = write!(
                out,
                "\n/** Unit enum ({}). Values decode to the case name. */\nexport type {} = {} | number;\n",
                cases.join(", "),
                e.name,
                names.join(" | "),
            );
        }

        for u in &spec.unions {
            let mut cases = Vec::with_capacity(u.cases.len());
            for c in &u.cases {
                if c.tys.is_empty() {
                    cases.push(format!("{:?}", c.name));
                } else {
                    let tys: Vec<String> = c.tys.iter().map(|ty| self.ts(ty, Pos::Ret)).collect();
                    cases.push(format!("{{ {}: [{}] }}", ts_key(&c.name), tys.join(", ")));
                }
            }
            let _ = write!(
                out,
                "\nexport type {} =\n  | {};\n",
                u.name,
                cases.join("\n  | "),
            );
        }

        out
    }

    /// One typed method per contract function.
    fn render_methods(&mut self) -> String {
        let mut out = String::new();
        let spec = self.spec;
        for f in &spec.functions {
            out.push('\n');
            out.push_str(&self.render_method(f));
        }
        out
    }

    fn render_method(&mut self, f: &FunctionSpec) -> String {
        let mut out = String::new();

        if !f.doc.trim().is_empty() {
            out.push_str("  /**\n");
            for line in f.doc.trim().lines() {
                // A `*/` in the doc must not terminate the comment early.
                let _ = writeln!(out, "   * {}", line.replace("*/", "*\\/"));
            }
            out.push_str("   */\n");
        }

        let ret = match f.output_tys.first() {
            Some(ty) => self.ts(ty, Pos::Ret),
            None => "null".into(),
        };

        // `constructor` is special in a TS class; a computed name sidesteps it
        // (and any name that isn't a valid identifier).
        let method = if is_ts_ident(&f.name) && f.name != "constructor" {
            f.name.clone()
        } else {
            format!("[{:?}]", f.name)
        };

        if f.inputs.is_empty() {
            let _ = writeln!(
                out,
                "  {method}(opts?: CallOptions): Promise<{ret}> {{\n    \
                 return this.invoke({:?}, {{}}, opts) as Promise<{ret}>;\n  }}",
                f.name,
            );
        } else {
            let params: Vec<String> = f
                .inputs
                .iter()
                .map(|i| {
                    let ty = self.ts(&i.ty, Pos::Arg);
                    format!("{}: {}", ts_key(&i.name), ty)
                })
                .collect();
            let _ = writeln!(
                out,
                "  {method}(args: {{ {} }}, opts?: CallOptions): Promise<{ret}> {{\n    \
                 return this.invoke({:?}, args, opts) as Promise<{ret}>;\n  }}",
                params.join("; "),
                f.name,
            );
        }
        out
    }
}

/// soroban-sdk names tuple-struct fields "0", "1", … — those encode (and
/// decode) positionally, so they become a TS tuple type rather than an object.
fn is_tuple_struct(s: &UdtStruct) -> bool {
    !s.fields.is_empty()
        && s.fields
            .iter()
            .all(|f| f.name.chars().all(|c| c.is_ascii_digit()))
}

fn is_ts_ident(s: &str) -> bool {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' || c == '$' => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
}

/// A field/parameter name as a TS object key, quoted only when it has to be.
fn ts_key(name: &str) -> String {
    if is_ts_ident(name) {
        name.to_string()
    } else {
        format!("{name:?}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use stellar_xdr::curr::{
        Limits, ScSpecEntry, ScSpecFunctionInputV0, ScSpecFunctionV0, ScSpecTypeDef,
        ScSpecTypeOption, ScSpecTypeUdt, ScSpecTypeVec, ScSpecUdtEnumCaseV0, ScSpecUdtEnumV0,
        ScSpecUdtStructFieldV0, ScSpecUdtStructV0, ScSpecUdtUnionCaseTupleV0, ScSpecUdtUnionCaseV0,
        ScSpecUdtUnionCaseVoidV0, ScSpecUdtUnionV0, ScSymbol, WriteXdr,
    };

    const C: &str = "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSC4";

    fn udt(name: &str) -> ScSpecTypeDef {
        ScSpecTypeDef::Udt(ScSpecTypeUdt {
            name: name.try_into().unwrap(),
        })
    }

    fn function(
        name: &str,
        doc: &str,
        inputs: Vec<(&str, ScSpecTypeDef)>,
        output: Option<ScSpecTypeDef>,
    ) -> ScSpecEntry {
        ScSpecEntry::FunctionV0(ScSpecFunctionV0 {
            doc: doc.try_into().unwrap(),
            name: ScSymbol(name.try_into().unwrap()),
            inputs: inputs
                .into_iter()
                .map(|(n, ty)| ScSpecFunctionInputV0 {
                    doc: "".try_into().unwrap(),
                    name: n.try_into().unwrap(),
                    type_: ty,
                })
                .collect::<Vec<_>>()
                .try_into()
                .unwrap(),
            outputs: output.into_iter().collect::<Vec<_>>().try_into().unwrap(),
        })
    }

    fn spec(entries: &[ScSpecEntry]) -> ContractSpec {
        let mut body = Vec::new();
        for e in entries {
            body.extend(e.to_xdr(Limits::none()).unwrap());
        }
        ContractSpec::from_spec_xdr(&body).expect("spec should parse")
    }

    fn full_spec() -> ContractSpec {
        // struct Position { borrower: Address, debt: i128 }
        let position = ScSpecEntry::UdtStructV0(ScSpecUdtStructV0 {
            doc: "".try_into().unwrap(),
            lib: "".try_into().unwrap(),
            name: "Position".try_into().unwrap(),
            fields: vec![
                ScSpecUdtStructFieldV0 {
                    doc: "".try_into().unwrap(),
                    name: "borrower".try_into().unwrap(),
                    type_: ScSpecTypeDef::Address,
                },
                ScSpecUdtStructFieldV0 {
                    doc: "".try_into().unwrap(),
                    name: "debt".try_into().unwrap(),
                    type_: ScSpecTypeDef::I128,
                },
            ]
            .try_into()
            .unwrap(),
        });
        // enum Status { Active = 0, Filled = 7 }
        let status = ScSpecEntry::UdtEnumV0(ScSpecUdtEnumV0 {
            doc: "".try_into().unwrap(),
            lib: "".try_into().unwrap(),
            name: "Status".try_into().unwrap(),
            cases: vec![
                ScSpecUdtEnumCaseV0 {
                    doc: "".try_into().unwrap(),
                    name: "Active".try_into().unwrap(),
                    value: 0,
                },
                ScSpecUdtEnumCaseV0 {
                    doc: "".try_into().unwrap(),
                    name: "Filled".try_into().unwrap(),
                    value: 7,
                },
            ]
            .try_into()
            .unwrap(),
        });
        // union Action { Cancel, Bid(i128) }
        let action = ScSpecEntry::UdtUnionV0(ScSpecUdtUnionV0 {
            doc: "".try_into().unwrap(),
            lib: "".try_into().unwrap(),
            name: "Action".try_into().unwrap(),
            cases: vec![
                ScSpecUdtUnionCaseV0::VoidV0(ScSpecUdtUnionCaseVoidV0 {
                    doc: "".try_into().unwrap(),
                    name: "Cancel".try_into().unwrap(),
                }),
                ScSpecUdtUnionCaseV0::TupleV0(ScSpecUdtUnionCaseTupleV0 {
                    doc: "".try_into().unwrap(),
                    name: "Bid".try_into().unwrap(),
                    type_: vec![ScSpecTypeDef::I128].try_into().unwrap(),
                }),
            ]
            .try_into()
            .unwrap(),
        });

        let vec_of_addr = ScSpecTypeDef::Vec(Box::new(ScSpecTypeVec {
            element_type: Box::new(ScSpecTypeDef::Address),
        }));
        let opt_u32 = ScSpecTypeDef::Option(Box::new(ScSpecTypeOption {
            value_type: Box::new(ScSpecTypeDef::U32),
        }));

        spec(&[
            position,
            status,
            action,
            function(
                "get_position",
                "Look up a borrower's position.",
                vec![("borrower", ScSpecTypeDef::Address)],
                Some(udt("Position")),
            ),
            function(
                "act",
                "",
                vec![("action", udt("Action")), ("hint", opt_u32)],
                Some(udt("Status")),
            ),
            function("holders", "", vec![], Some(vec_of_addr)),
            function("reset", "", vec![], None),
        ])
    }

    #[test]
    fn generates_types_for_every_udt_shape() {
        let ts = typescript_client(C, &full_spec());
        assert!(ts.contains("export interface Position {\n  borrower: Address;\n  debt: i128;\n}"));
        assert!(ts.contains(r#"export type Status = "Active" | "Filled" | number;"#));
        assert!(ts.contains("export type Action =\n  | \"Cancel\"\n  | { Bid: [i128] };"));
    }

    #[test]
    fn generates_typed_methods() {
        let ts = typescript_client(C, &full_spec());
        assert!(ts.contains("Look up a borrower's position."));
        assert!(ts.contains(
            "get_position(args: { borrower: Address }, opts?: CallOptions): Promise<Position>"
        ));
        assert!(ts.contains(
            "act(args: { action: Action; hint: number | null }, opts?: CallOptions): Promise<Status>"
        ));
        // Zero-arg function takes only options; void function resolves null.
        assert!(ts.contains("holders(opts?: CallOptions): Promise<Address[]>"));
        assert!(ts.contains("reset(opts?: CallOptions): Promise<null>"));
        assert!(ts.contains(C));
    }

    #[test]
    fn emits_only_the_aliases_the_interface_uses() {
        let ts = typescript_client(C, &full_spec());
        assert!(ts.contains("export type Address = string;"));
        assert!(ts.contains("export type i128 = number | string;"));
        // Nothing in the interface touches these.
        assert!(!ts.contains("export type u256"));
        assert!(!ts.contains("export type Duration"));
    }

    #[test]
    fn tuple_structs_become_tuple_types() {
        let pair = ScSpecEntry::UdtStructV0(ScSpecUdtStructV0 {
            doc: "".try_into().unwrap(),
            lib: "".try_into().unwrap(),
            name: "Pair".try_into().unwrap(),
            fields: vec![
                ScSpecUdtStructFieldV0 {
                    doc: "".try_into().unwrap(),
                    name: "0".try_into().unwrap(),
                    type_: ScSpecTypeDef::Address,
                },
                ScSpecUdtStructFieldV0 {
                    doc: "".try_into().unwrap(),
                    name: "1".try_into().unwrap(),
                    type_: ScSpecTypeDef::U32,
                },
            ]
            .try_into()
            .unwrap(),
        });
        let ts = typescript_client(C, &spec(&[pair]));
        assert!(ts.contains("export type Pair = [Address, number];"));
    }

    #[test]
    fn awkward_function_names_get_computed_keys() {
        let s = spec(&[function(
            "constructor",
            "",
            vec![],
            Some(ScSpecTypeDef::U32),
        )]);
        let ts = typescript_client(C, &s);
        assert!(ts.contains(r#"["constructor"](opts?: CallOptions): Promise<number>"#));
    }

    #[test]
    fn output_is_deterministic() {
        let ts = typescript_client(C, &full_spec());
        assert_eq!(ts, typescript_client(C, &full_spec()));
        // Dump for an external `tsc` compile check during development.
        if let Ok(path) = std::env::var("CODEGEN_DUMP") {
            std::fs::write(path, &ts).unwrap();
        }
    }
}
